root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 0
  exclude_dir = ["node_modules", "assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include = ["**/*.go"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true
  poll_interval = 1000
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false
